export const teacherTeamItems = [
  {
    id: 1,
    avatarImg: "https://ui-avatars.com/api/?name=F+A",
    name: "Fatima Akter",
    email: "fatima.akter@example.com",
    headline: "Early Math & Counting Guide",
    info: "Fatima makes numbers fun by using games and stories, helping kids build a strong foundation in math through engaging activities.",
  },
  {
    id: 2,
    avatarImg: "https://ui-avatars.com/api/?name=A+R",
    name: "Abdul Rahman",
    email: "abdul.rahman@example.com",
    headline: "Fun Science & Nature Explorer",
    info: "Abdul introduces young minds to the wonders of nature, using simple experiments and observations to spark curiosity in science.",
  },
  {
    id: 3,
    avatarImg: "https://ui-avatars.com/api/?name=S+J",
    name: "Sharmin Jahan",
    email: "sharmin.jahan@example.com",
    headline: "Stories & Imagination Coach",
    info: "Sharmin helps kids dive into colorful worlds through stories, encouraging creativity and self-expression through playful reading.",
  },
  {
    id: 4,
    avatarImg: "https://ui-avatars.com/api/?name=R+H",
    name: "Rafiq Hasan",
    email: "rafiq.hasan@example.com",
    headline: "Friendly Computer Basics Mentor",
    info: "Rafiq introduces children to computers with simple games and interactive tools, making digital learning fun and approachable.",
  },
  {
    id: 5,
    avatarImg: "https://ui-avatars.com/api/?name=N+A",
    name: "Nasreen Ahmed",
    email: "nasreen.ahmed@example.com",
    headline: "Little Historians Guide",
    info: "Nasreen tells exciting stories about famous events in a fun way, helping kids learn history through adventure and imagination.",
  },
  {
    id: 6,
    avatarImg: "https://ui-avatars.com/api/?name=T+H",
    name: "Tanvir Hossain",
    email: "tanvir.hossain@example.com",
    headline: "Playful Biology & Animal Friend",
    info: "Tanvir teaches children about animals and nature using fun facts and outdoor activities to make learning about life sciences exciting.",
  },
];
